### ISSUE TITLE
Help with characteristics

### ISSUE THREAD

**Issue by ZaubererMD** [neonightmare/homebridge-yamaha#7]
Hey there,
I tried out this plugin and since it does not yet support a lot of options I tried expanding it. When adding new characteristics to this, my homebridge will always crash without any error message after discovering my yamaha and trying to set it up. This even happens when I copy&paste your custom characteristics and only change the name and UUID. It's like homebridge has a problem with my new characteristic, but I dont know why.
Can you give me some hints what to do when adding new characteristics?
The UUID I used was just the same as your Muting-Characteristic, I just replaced 1002 with 1003. Is that OK? Or is there anything else I need to be aware of when choosing a UUID?
Also note that I was working on the index.js in a "productive" environment, not in some debug or development mode. I just edited the file in the node_modules folder. Might this be a problem?

**Comment by SphtKr** [comment]
Hmm....no, there's no reason that Homebridge should care about the custom characteristics or their UUIDs. The iOS apps yes, and they could theoretically crash, sure, but Homebridge shouldn't care. Have you forked this repo? Can you do so and commit some code so we can see?

Also, since we're talking about custom characteristics, be aware that if you're making custom characteristics, neither Siri nor third-party apps will know what to do with them--automatically at least. Unless you're writing your own iOS app, they'll (probably, mostly, with some caveats) be useless.

**Comment by ZaubererMD** [comment]
Tried it again today to push it to my fork, so you can see it, but now it suddenly works. Classical heisenbug... Might have something to do with the name of my characteristic, I used to name it PlayStatus and now I used just Play. Anyway, After this worked I wanted to implement the actual play-control since it just mirrored the power-status at that time, but then I realized there is no way to read the play-status from the yamaha AVR. Some interface restrictions are just so terribly stupid, I don't get it.

Thank you for your help anyway.
